update tencentcloud
GoogleCloudPlatform/terraformer pull request #1315
Opened 2022-05-05 12:21 UTC by hellertang

2022-05-06 20:11 UTC, sergeylanzman requested changes

2022-05-06 20:11 UTC, sergeylanzman commented on providers/tencentcloud/gaap.go
> +		if err := g.loadRealServer(client); err != nil {
Function  loadRealServer still?

2022-05-06 20:11 UTC, sergeylanzman commented on providers/tencentcloud/gaap.go
> +		if err := g.loadCertificate(client); err != nil {
same?

2022-05-06 20:11 UTC, sergeylanzman commented on providers/tencentcloud/subnet.go
> +		name := "is-default"
if it's not in use please delete

2022-05-06 20:11 UTC, sergeylanzman commented on providers/tencentcloud/vpc.go
> +		defaultName := "is-default"
same

2022-05-07 07:30 UTC, hellertang commented on providers/tencentcloud/gaap.go
> +		if err := g.loadRealServer(client); err != nil {
fix

2022-05-07 07:30 UTC, hellertang commented on providers/tencentcloud/gaap.go
> +		if err := g.loadCertificate(client); err != nil {
fix

2022-05-07 07:31 UTC, hellertang commented on providers/tencentcloud/vpc.go
> +		defaultName := "is-default"
fix

2022-05-07 07:31 UTC, hellertang commented on providers/tencentcloud/subnet.go
> +		name := "is-default"
fix

2022-05-07 10:21 UTC, sergeylanzman approved these changes

2022-05-07 10:21 UTC, merged