Add support for IBM cloud provider
GoogleCloudPlatform/terraformer pull request #663
Opened 2020-11-12 12:13 UTC by anilkumarnagaraj

This PR adds support for IBM CLOUD provider. 

**List of supported resources:**

*   `ibm_cos`
    * `ibm_resource_instance`
    * `ibm_cos_bucket`
*   `ibm_iam`
    * `ibm_iam_user_policy`
    * `ibm_iam_access_group`
    * `ibm_iam_access_group_members`
    * `ibm_iam_access_group_policy`
    * `ibm_iam_access_group_dynamic_rule`
*   `ibm_container_vpc_cluster`
    * `ibm_container_vpc_cluster`
    * `ibm_container_vpc_worker_pool`
*   `ibm_database_etcd`
    * `ibm_database`
*   `ibm_database_mongo`
    * `ibm_database`
*   `ibm_database_postgresql`
    * `ibm_database`
*   `ibm_database_rabbitmq`
    * `ibm_database`
*   `ibm_database_redis`
    * `ibm_database`
*   `ibm_is_instance_group`
    * `ibm_is_instance_group`
    * `ibm_is_instance_group_manager`
    * `ibm_is_instance_group_manager_policy`
*   `ibm_is_vpc`
    * `ibm_is_vpc`
    * `ibm_is_vpc_address_prefix`
    * `ibm_is_vpc_route`
*   `ibm_is_subnet`
*   `ibm_is_instance`
*   `ibm_is_security_group`
    * `ibm_is_security_group_rule`

2020-11-12 13:37 UTC, sergeylanzman commented on README.md
> +If you want to run Terraformer with the IBM Cloud provider plugin on your system, complete the following steps:
It's same process for all providers, you can delete 1-6.

2020-11-12 13:43 UTC, sergeylanzman commented on providers/ibm/cos.go
> +			singleSiteLocationRegex, _ := regexp.Compile("^[a-z]{3}[0-9][0-9]-[a-z]{4,8}$")
Can you move regex outside loops? for better performance

2020-11-12 13:44 UTC, sergeylanzman commented on providers/ibm/database_elasticsearch.go
> +// Copyright 2019 The Terraformer Authors.
License first

2020-11-12 13:44 UTC, sergeylanzman commented on providers/ibm/database_etcd.go
> +// Copyright 2019 The Terraformer Authors.
License first

2020-11-12 13:44 UTC, sergeylanzman commented on providers/ibm/database_mongo.go
> +// Copyright 2019 The Terraformer Authors.
License first

2020-11-12 13:45 UTC, sergeylanzman commented on providers/ibm/database_postgresql.go
> +// Licensed under the Apache License, Version 2.0 (the "License");
same

2020-11-12 13:45 UTC, sergeylanzman commented on providers/ibm/database_postgresql.go
> +	log.Printf("Resources list %+v", resources)
delete log.Printf

2020-11-12 13:45 UTC, sergeylanzman commented on providers/ibm/database_rabbitmq.go
> +// Licensed under the Apache License, Version 2.0 (the "License");
same

2020-11-12 13:47 UTC, sergeylanzman commented on providers/ibm/iam.go
> +		time.Now().UTC().String(),
It's generate every time other IDs, Maybe better take hash or combine.

Some people run terraformer many time and check git diff

2020-11-12 13:48 UTC, sergeylanzman commented on providers/ibm/ibm_is_instance.go
> +		log.Fatal("No API key set")
no fatal, please return error

2020-11-12 13:48 UTC, sergeylanzman commented on providers/ibm/ibm_is_security_group.go
> +		log.Fatal("No API key set")
return error

2020-11-12 13:48 UTC, sergeylanzman commented on providers/ibm/ibm_is_subnet.go
> +		log.Fatal("No API key set")
return error

2020-11-12 13:49 UTC, sergeylanzman commented on providers/ibm/ibm_is_vpc.go
> +		log.Fatal("No API key set")
return error

2020-11-12 13:51 UTC, sergeylanzman commented on providers/ibm/ibm_provider.go
> +				"version": providerwrapper.GetProviderVersion(p.GetName()),
not need anymore https://github.com/GoogleCloudPlatform/terraformer/blob/6794a293fcb931c538821a3a67db274fdde89343/terraformutils/terraformoutput/hcl.go#L37

2020-11-12 13:58 UTC, sergeylanzman commented on providers/ibm/instance_groups.go
> +		go g.handleManagers(sess, instanceGoupID, managers)
I don't see any wait for finish work in all goroutines.

2020-11-12 13:59 UTC, sergeylanzman commented on providers/ibm/instance_groups.go
> +		go g.handlePolicies(sess, instanceGroupID, instanceGroupManagerID, policies)
I don't see any wait for finish work in all goroutines.

2020-11-12 13:59 UTC, sergeylanzman commented on providers/ibm/instance_groups.go
> +		log.Fatal("No API key set")
return error

2020-11-12 14:00 UTC, sergeylanzman commented on providers/ibm/kp.go
> +	client.Config.InstanceID = "e63cc5b3-2594-4e13-b1b1-e8263095ff4b"
??

2020-11-12 14:00 UTC, sergeylanzman commented on providers/ibm/utils.go
> +package ibm
licence

2020-11-12 14:01 UTC, sergeylanzman commented on providers/ibm/instance_groups.go
> +		log.Println("Done Importing")
delete log

2020-11-12 14:01 UTC, sergeylanzman commented on providers/ibm/instance_groups.go
> +		log.Fatal("Error creating VPC Service.")
only return error

2020-11-12 14:02 UTC, sergeylanzman commented on providers/ibm/instance_groups.go
> +		log.Fatal("Error: ", err)
only return error

2020-11-12 14:05 UTC, sergeylanzman commented
@anilkumarnagaraj Good job! thanks!!
Few issues:
1. signed CLA
2. delete logs.println in resources
3. delete logs.fatal and return error. logs.Fatal exit program, if you want import many resources, one of them can close program
4. licence in files
5. goroutines issue - I don't find any line with wait for finished in all goroutines

2020-12-07 09:11 UTC, sergeylanzman commented
@anilkumarnagaraj Can you signed CLA?

2020-12-07 12:59 UTC, anilkumarnagaraj commented
@googlebot I signed it!

2020-12-08 10:48 UTC, sergeylanzman requested changes
3 issues:
1. https://github.com/GoogleCloudPlatform/terraformer/pull/663/files#diff-050bd2042edc200aeca4f15ef0cf63b438b1e1fbe9491f4b23ab2f8d4b59ef01R100
2. https://github.com/GoogleCloudPlatform/terraformer/pull/663/files#diff-8ec0974ea9817845502d6f7d5d9a1bb74ad7f8f23f4c96e54c2d7dad7b61e232R61
3. https://github.com/GoogleCloudPlatform/terraformer/pull/663/files#diff-63a9aae40d8899f9c4b20c1d7efadd157dd241250158a5298df3f307045e51c4R1

2020-12-08 12:04 UTC, merged